Repository piyushpatelcodes/gssocFAQ-Bot, pull requests merged in 2025-07, with the labels that each got.

#2 Added FAQ
  faqs.json
  package-lock.json
  package.json
Labels: enhancement, GSSOC 2025, Level 1

#4 Added try catch block to index.js file
  index.js
Labels: GSSOC 2025, Level 2

#36 Add MIT LICENSE file
  LICENSE
Labels: GSSOC'25, Level 1
